version: "3.9"
services:

  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    volumes:
      - ./compose/mosquitto/data:/mosquitto/data

  booking:
    build: 
      context: .
      dockerfile: ./apps/booking/Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./:/service
    depends_on:
      - mqtt

  payment:
    build: 
      context: .
      dockerfile: ./apps/payment/Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./:/service
    depends_on:
      - mqtt