version: "3.9"
services:
  mongo:
    image: bitnami/mongodb:latest
    env_file:
      - .env
    volumes:
      - ./compose/mongo:/bitnami/mongodb
  mqtt:
    image: eclipse-mosquitto:latest
    volumes:
      - ./compose/mosquitto/data:/mosquitto/data
      - ./compose/mosquitto/config:/mosquitto/config

  booking:
    build: 
      context: .
      dockerfile: ./apps/booking/Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./:/service
    depends_on:
      - mqtt
      - mongo
  payment:
    build: 
      context: .
      dockerfile: ./apps/payment/Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./:/service
    depends_on:
      - mqtt
      - mongo