version: "3.9"
services:
  mqtt:
    image: eclipse-mosquitto:latest
    volumes:
      - ./compose/mosquitto/data:/mosquitto/data
      - ./compose/mosquitto/config:/mosquitto/config
  booking:
    build: 
      context: .
      dockerfile: ./apps/booking/Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./:/service
    depends_on:
      - mqtt
    ports:
      - 3001:3001
  payment:
    build: 
      context: .
      dockerfile: ./apps/payment/Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./:/service
    depends_on:
      - mqtt