const { 
  MQTT_URL,
  MONGO_INITDB_ROOT_USERNAME,
  MONGO_INITDB_ROOT_PASSWORD
} = process.env;

export const rootConfig = Object.freeze({
  MQTT_URL,
  MONGO_INITDB_ROOT_USERNAME,
  MONGO_INITDB_ROOT_PASSWORD
})